name: flutter_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.6.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  freezed: ^2.4.7
  injectable: ^2.4.4
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0
  dartz: ^0.10.1
  internet_connection_checker: ^2.0.0
  get_it: ^7.7.0
  freezed_annotation: ^2.4.4
  form_validator: ^2.1.1
  go_router: ^14.2.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
