// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwCcfiuQirM7Kjqd8Mv6SLCp6z_VqWIjU',
    appId: '1:872799367936:web:277f6b509bf1a76a5b79e5',
    messagingSenderId: '872799367936',
    projectId: 'flutter-task-81166',
    authDomain: 'flutter-task-81166.firebaseapp.com',
    storageBucket: 'flutter-task-81166.appspot.com',
    measurementId: 'G-7008HTZEG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkR70RAfNJcfgnrvJCw9nmkG5ibJpD4Qs',
    appId: '1:872799367936:android:9b4706a37434f3fc5b79e5',
    messagingSenderId: '872799367936',
    projectId: 'flutter-task-81166',
    storageBucket: 'flutter-task-81166.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWFED0LqBO6YIyBkrt5c2xh0kZUbqDGD0',
    appId: '1:872799367936:ios:bf08d7cb2eb1de225b79e5',
    messagingSenderId: '872799367936',
    projectId: 'flutter-task-81166',
    storageBucket: 'flutter-task-81166.appspot.com',
    iosBundleId: 'com.example.flutterTask',
  );
}
